apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-alim-config
data:
  application-dev.yml: |
    server:
      port: 8080
    spring:
      kafka:
        bootstrap-servers: k8s-external-kafka-service:9092